СryptoFacilitiesAdapterService:
    Db:
        LogsConnectionString:
            settings-key: СryptoFacilitiesAdapterService-LogsConnectionString
            types:
              - AzureTableStorage
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

